### ISSUE TITLE
RuntimeError and Code details

### ISSUE THREAD

**Issue by lovelyczli** [icoz69/DeepEMD#28]
Thanks for your interesting work. And I have two questions:
Q1. When I train (meta-train) the model with 4 gpus with qpth solver, I get the RuntimeError(at the bottom). But when meta-training the model with 3 gpus with qpth solver, it is available  (but with Warning: [W TensorIterator.cpp:924] Warning: Mixed memory format inputs detected while calling the operator. The operator will output channels_last tensor even if some of the inputs are not in channels_last format. (function operator()) ).  
And it is ok when pretraining or meta-training with opcv solver with any numbers of gpus(however there still exists Warning:).

2. What are they trying to do in the opencv solver? specifically, 
    1) line 5 and line 8 calculate the dot product between flow and similarity, but in transportation problem, we aim to calculate the dot product between flow and cost, so is it miss the (1-similarity_map[i, j, :, :]) in line 5? and why not use the cost computed by opencv?
   2) what is the meaning of the temperature in line 7, and it is like that temperature is a scale factor for logitis? 

      line0:     for i in range(num_query):
      line1:          for j in range(num_proto):
      line2:              # similarity, weight_1, weight_2 index [i, j]; cost = 1 - similarity
      line3:              _, flow = emd_inference_opencv(1 - similarity_map[i, j, :, :], weight_1[i, j, :], weight_2[j, i, :])
      line4:              # _: cost; flow
      line5:              similarity_map[i, j, :, :] = (similarity_map[i, j, :, :]) * torch.from_numpy(flow).cuda()
      line6:
      line7:      temperature = (self.args.temperature/num_node)
      line8:      logitis = similarity_map.sum(-1).sum(-1) * temperature      # (tensor([75,5])
      line9:      return logitis
   3)whyc v2.EMD is much faster than qpth? do they use different algorithm? is it necessary to use relu and normalize before EMD?
   4) It is obvious that gradient don't bp, so do you only update structed_fc when training with opcv and the encoder is fixed?

def emd_inference_opencv(cost_matrix, weight1, weight2):
    # (tensor([25,25]), tensor([25]), tensor([25]))
    # cost matrix is a tensor of shape [N,N]
    cost_matrix = cost_matrix.detach().cpu().numpy()
    # ensure > 0
    weight1 = F.relu(weight1) + 1e-5
    weight2 = F.relu(weight2) + 1e-5
    # normalize to 1
    weight1 = (weight1 * (weight1.shape[0] / weight1.sum().item())).view(-1, 1).detach().cpu().numpy()
    weight2 = (weight2 * (weight2.shape[0] / weight2.sum().item())).view(-1, 1).detach().cpu().numpy()

    cost, _, flow = cv2.EMD(weight1, weight2, cv2.DIST_USER, cost_matrix)
    # a transportation problem, solved using a simplex algorithm
    # the complexity is exponential in the worst case
    # multi-dimensional histogram comparison for image retrieval
    return cost, flow

Looking forward to your reply! Many thanks for your help!

________________________][W TensorIterator.cpp:924] Warning: Mixed memory format inputs detected while calling the operator. The operator will output channels_last tensor even if some of the inputs are not in channels_last format. (function operator())
epo 1, total loss=0.6705 acc=0.8533:  10%|███████████▍                                                                                                      | 5/50 [02:08<19:13, 25.63s/it]
Traceback (most recent call last):
  File "train_meta.py", line 170, in <module>
    total_loss.backward()
  File "/home/lichangzhen/anaconda3/envs/pytorch1.7/lib/python3.6/site-packages/torch/tensor.py", line 185, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/lichangzhen/anaconda3/envs/pytorch1.7/lib/python3.6/site-packages/torch/autograd/__init__.py", line 127, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: The shape of the mask [95, 675, 675] at index 0 does not match the shape of the indexed tensor [90, 675, 675] at index 0
______________________________________________________________________________________

**Comment by lovelyczli** [comment]
Following all your setting(without modifying the code).
I get the following results on miniiamgenet:
train_pretrain(4 gpus): val Acc 0.6544
train_meta(opencv, 4gpus): val Acc 0.6703  test Acc 65.5653
train_meta(qpth, 3gpus): val Acc 0.6738  test Acc 66.0779
Does using 3 gpus bring about the performance degradation?
@icoz69 Looking forward to your reply!

**Comment by icoz69** [comment]
hi thank your for your interests in our work.
1. this might be a bug in QPTH solver and I did not know the reason for now.
2.  basically, you use cost to compute flow， where the cost is the '1 - similarity' (Line 3). After you get the flow, you use the flow to represent the similarity score, which combines flows and similarity matrix. So, here the result is EARTH MOVER'S SIMILARITY. Temperature is to scale the logits.
3. V2 use opencv as solver. Opencv is much faster than QPTH.
4. yes
5. the performance looks normal. The minor difference with the paper may be caused by random seed.

**Comment by zeakey** [comment]
HI @icoz69 , a nice work!

As you mentioned, in V2 you used the `cv2.EMD` to calculate the optimal transport. So how did you obtain the gradient of
EMD when calculating it outside torch?

Did you hard-code the gradient, or the gradient is unnecessary in your method?
