### ISSUE TITLE
pre_train with grid/sampling mode error

### ISSUE THREAD

**Issue by yohann84L** [icoz69/DeepEMD#31]
Hi, I'm trying to pre train with grid or sampling mode but I have an error.

This is due to encode function when using patches: the outputs features are size `(batch_size, feature_size=640, number_patchs)` which can not be fed into Linear layer. How do you resize the outputs features of patches to feed properly into the linear layer ?

The complete error:
```
Traceback (most recent call last):
  File "train_pretrain.py", line 119, in <module>
    logits = model(data)
  File "/home/ubuntu/yohann/DeepEMD/deepemdenv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/yohann/DeepEMD/deepemdenv/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 159, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/ubuntu/yohann/DeepEMD/deepemdenv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/yohann/DeepEMD/src/models/deep_emd.py", line 29, in forward
    return self.pre_train_forward(input)
  File "/home/ubuntu/yohann/DeepEMD/src/models/deep_emd.py", line 41, in pre_train_forward
    return self.fc(self.encode(input, dense=False).squeeze(-1).squeeze(-1))
  File "/home/ubuntu/yohann/DeepEMD/deepemdenv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/yohann/DeepEMD/deepemdenv/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 93, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/ubuntu/yohann/DeepEMD/deepemdenv/lib/python3.6/site-packages/torch/nn/functional.py", line 1692, in linear
    output = input.matmul(weight.t())
RuntimeError: mat1 dim 1 must match mat2 dim 0
```

**Comment by icoz69** [comment]
hi the choice of deepemd mode in pre-training is only used for validation, so there is no need to use Grid and sampling.
